["Example Device"]
ip = "localhost"
port = "22"
username = "admin"
password = "admin"
enable_password = "admin"
device_type = "ios"

[ASR1002X]
ip = "F340-08-16-COMM"
port = "2008"
username = "admin"
password = "cisco!123"
enable_password = ""
device_type = "ios"
